export const ACTION_TYPE__CLIENT_IN = 'CLIENT_IN'
export const ACTION_TYPE__CLIENT_OUT = 'CLIENT_OUT'
export const ACTION_TYPE__MESSAGE_CREATED = 'MESSAGE_CREATED'
export const ACTION_TYPE__MESSAGES_UPDATE = 'MESSAGES_UPDATE'
